function Vibr01 () {
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
}
radio.onReceivedNumber(function (receivedNumber) {
    if (receivedNumber == 0) {
        Vibr01()
    } else if (receivedNumber == 1) {
        Vibr02()
    } else if (receivedNumber == 2) {
        Vibr03()
    }
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    strip.showColor(neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(20, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(17, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(16, neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(15, neopixel.colors(NeoPixelColors.White))
    strip.show()
    strip.clear()
    strip.show()
})
input.onButtonPressed(Button.A, function () {
    Vibr01()
    seq = 0
})
input.onButtonPressed(Button.AB, function () {
    Vibr03()
    seq = 2
})
input.onButtonPressed(Button.B, function () {
    Vibr02()
    seq = 1
})
input.onGesture(Gesture.Shake, function () {
    if (seq == 0) {
        Vibr01()
        radio.sendNumber(0)
    } else if (seq == 1) {
        Vibr02()
        radio.sendNumber(1)
    } else if (seq == 2) {
        Vibr03()
        radio.sendNumber(2)
    }
    basic.pause(200)
    strip.showColor(neopixel.colors(NeoPixelColors.White))
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(20, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Black))
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Black))
    strip.show()
    strip.clear()
    strip.show()
})
function Vibr03 () {
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
}
function Vibr02 () {
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.pause(50)
    pins.digitalWritePin(DigitalPin.P1, 0)
}
let seq = 0
let strip: neopixel.Strip = null
radio.setGroup(1)
strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
let L01 = strip.range(0, 6)
let L02 = strip.range(15, 21)
basic.forever(function () {
    if (grove.measureInCentimetersV2(DigitalPin.P2) <= 5) {
        pins.digitalWritePin(DigitalPin.P1, 1)
        basic.pause(100)
        pins.digitalWritePin(DigitalPin.P1, 0)
        L01.showColor(neopixel.colors(NeoPixelColors.White))
        L02.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(200)
        L01.showColor(neopixel.colors(NeoPixelColors.Black))
        L02.showColor(neopixel.colors(NeoPixelColors.Black))
        basic.pause(200)
        L01.showColor(neopixel.colors(NeoPixelColors.White))
        L02.showColor(neopixel.colors(NeoPixelColors.White))
        basic.pause(300)
        L01.showColor(neopixel.colors(NeoPixelColors.Black))
        L02.showColor(neopixel.colors(NeoPixelColors.Black))
        basic.pause(500)
    }
})
